"""empty message

Revision ID: 93c2fa0cf835
Revises: bf5cc48b33b5
Create Date: 2024-07-29 22:29:52.346555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c2fa0cf835'
down_revision = 'bf5cc48b33b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Path', schema=None) as batch_op:
        batch_op.alter_column('title_name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('img',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_constraint('Path_difficulty_key', type_='unique')
        batch_op.drop_constraint('Path_title_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Path', schema=None) as batch_op:
        batch_op.create_unique_constraint('Path_title_name_key', ['title_name'])
        batch_op.create_unique_constraint('Path_difficulty_key', ['difficulty'])
        batch_op.alter_column('img',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('title_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
