"""empty message

Revision ID: a4b771f3a521
Revises: f52d7eee7918
Create Date: 2024-07-30 00:18:01.807999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b771f3a521'
down_revision = 'f52d7eee7918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint('User_path_id_fkey', type_='foreignkey')
        batch_op.drop_column('path_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('User_path_id_fkey', 'Path', ['path_id'], ['id'])

    # ### end Alembic commands ###
