"""empty message

Revision ID: c2ff45d7d226
Revises: 9a353acf89e4
Create Date: 2024-07-22 23:44:23.591397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ff45d7d226'
down_revision = '9a353acf89e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Group', schema=None) as batch_op:
        batch_op.alter_column('path_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'Path', ['path_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('path_id')

    with op.batch_alter_table('Group', schema=None) as batch_op:
        batch_op.alter_column('path_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
