"""empty message

Revision ID: f52d7eee7918
Revises: c2ff45d7d226
Create Date: 2024-07-23 01:25:48.903735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f52d7eee7918'
down_revision = 'c2ff45d7d226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FavoritePath',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['Path.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GroupMember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['Group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Group Member')
    op.drop_table('Favorite Path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Favorite Path',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Favorite Path_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('path_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['Path.id'], name='Favorite Path_path_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='Favorite Path_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Favorite Path_pkey')
    )
    op.create_table('Group Member',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Group Member_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['Group.id'], name='Group Member_group_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='Group Member_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Group Member_pkey')
    )
    op.drop_table('GroupMember')
    op.drop_table('FavoritePath')
    # ### end Alembic commands ###
